name: Qiita Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  qiita_sync_check:
    name: Run qiita-sync sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install qiita-sync
        run: |
          python -m pip install qiita-sync
      - name: Run qiita-sync
        run: |
          qiita_sync sync .
        env: 
          QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config core.quotepath false
          find . -name '*.md' -not -path './.*' -exec git add {} + || true
          if ! git diff --staged --exit-code --quiet
          then
            git commit -m "updated by qiita-sync"
            git push
          fi
